dscorp_usuario:
    resource: "@DscorpUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

vista:
    resource: "@VistaBundle/Resources/config/routing.yml"
    prefix:   /

dscorp_admin:
    resource: "@DscorpAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

login:
    pattern:   /login
    defaults:  { _controller: DscorpUsuarioBundle:Security:login }
login_check:
    pattern:   /login_check

usuario_create_login:
    pattern:  /create_login
    defaults: { _controller: DscorpUsuarioBundle:Security:create_login }
    requirements: { _method: post }
