vista_homepage:
    pattern:  /
    defaults: { _controller: VistaBundle:Default:vista }
vista:
    pattern:  /dscorp/es/
    defaults: { _controller: VistaBundle:Default:vista }
lenguaje:
    pattern:  /dscorp/{id}/
    defaults: { _controller: VistaBundle:Default:lenguaje }
include_header:
    pattern:  /include/header/
    defaults: { _controller: VistaBundle:Include:header }
include_sidebar:
    pattern:  /include/sidebar/
    defaults: { _controller: VistaBundle:Include:sidebar }
include_footer:
    pattern:  /include/footer/
    defaults: { _controller: VistaBundle:Include:footer }
include_content:
    pattern:  /include/content/{id}
    defaults: { _controller: VistaBundle:Include:content}