Dscorp\VistaBundle\Entity\Prueba:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        prueba:
            type: string
            length: 255
    lifecycleCallbacks: {  }
