Dscorp\UsuarioBundle\Entity\Role:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreRole:
            type: string
            length: 255
    lifecycleCallbacks: {  }
